apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
  name: pattern-sample
spec:
  clusterGroupName: hub
  gitSpec:
    targetRepo: "https://github.com/validatedpatterns/multicloud-gitops"
    targetRevision: "main"
    multiSourceSupport: false

