name: "Docker Build"
on: [push, pull_request]

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: make docker-build
