name: "Docker Build"
on: [push, pull_request]

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        env:
          KEY: ${{ secrets.API_KEY }}
        shell: bash
        run: |
          set -e
          export APIFILE="controllers/apikey.txt"
          trap "rm -f ${APIFILE}" SIGINT EXIT

          if [ -z "${KEY}" ]; then
              echo "Key is empty"
              echo '' > "${APIFILE}"
          else
              echo "Key is set"
              echo "${KEY}" > "${APIFILE}"
          fi
          make docker-build
